name: Kitchen Backend CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Pull
      uses: actions/checkout@v3
    - name: Build
      run: docker-compose up --build -d
